"""
Gemini_Engine/main.py
=====================
Orchestrates the complete Gemini workflow:
1. Loads graph_summary.json, rule_validation.json, and timeline.json.
2. Combines them into a single investigation context.
3. Compiles a professional forensic analysis prompt.
4. Queries Gemini model for comprehensive markdown analysis.
5. Saves the output to Gemini_Engine/outputs/investigation_report.md.

Run:
    cd backend
    python -m Gemini_Engine.main
"""

import json
import os
import sys
from pathlib import Path

# Ensure package imports work smoothly
sys.path.insert(0, str(Path(__file__).parent.parent))

from Gemini_Engine.gemini_client import generate_report

# Live source directories of the 3 outputs
BASE_DIR = Path(__file__).parent.parent
REAL_SUMMARY_PATH = BASE_DIR / "analysis" / "graph_summary" / "summary.json"
REAL_FLAGS_PATH   = BASE_DIR / "analysis" / "rule_validation" / "output" / "flags.json"
REAL_PROFILES_PATH = BASE_DIR / "analysis" / "rule_validation" / "output" / "person_risk_profiles.json"
REAL_REL_PROFILES_PATH = BASE_DIR / "analysis" / "rule_validation" / "output" / "relationship_risk_profiles.json"
REAL_TIMELINE_PATH = BASE_DIR / "analysis" / "timeline_reconstruction" / "timeline.json"


# Local fallback directories as per gemini_engine_implementation.md
LOCAL_INPUTS_DIR = Path(__file__).parent / "inputs"
LOCAL_OUTPUTS_DIR = Path(__file__).parent / "outputs"


def load_json_file(primary_path: Path, fallback_filename: str) -> dict:
    """Load JSON from the primary path, or fallback to the local inputs folder."""
    fallback_path = LOCAL_INPUTS_DIR / fallback_filename
    
    if primary_path.exists():
        print(f"[Gemini Engine] Reading live input: {primary_path.name} from {primary_path.parent}")
        try:
            with open(primary_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            print(f"[Gemini Engine] Error reading {primary_path.name}: {e}")
            
    # Try local inputs fallback
    if fallback_path.exists():
        print(f"[Gemini Engine] Reading fallback input: {fallback_path.name} from {LOCAL_INPUTS_DIR}")
        try:
            with open(fallback_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            print(f"[Gemini Engine] Error reading fallback {fallback_filename}: {e}")
            
    print(f"[Gemini Engine] Warning: Could not find '{primary_path.name}' at either live or fallback locations!")
    return {}


def run_engine():
    # Ensure folders exist
    LOCAL_INPUTS_DIR.mkdir(exist_ok=True)
    LOCAL_OUTPUTS_DIR.mkdir(exist_ok=True)
    
    print("[Gemini Engine] Loading inputs...")
    graph_summary   = load_json_file(REAL_SUMMARY_PATH, "graph_summary.json")
    rule_validation = load_json_file(REAL_FLAGS_PATH, "rule_validation.json")
    person_profiles = load_json_file(REAL_PROFILES_PATH, "person_risk_profiles.json")
    relationship_profiles = load_json_file(REAL_REL_PROFILES_PATH, "relationship_risk_profiles.json")
    timeline        = load_json_file(REAL_TIMELINE_PATH, "timeline.json")
    
    # Verify we have at least some context
    if not graph_summary and not rule_validation and not person_profiles and not timeline:
        print("[Gemini Engine] ERROR: All input files are empty or missing! Run previous pipeline steps first.")
        sys.exit(1)
        
    print("[Gemini Engine] Constructing forensic context...")
    context = {
        "graph_summary": graph_summary,
        "rule_validation": rule_validation,
        "person_profiles": person_profiles,
        "relationship_profiles": relationship_profiles,
        "timeline": timeline
    }
    
    # Format a beautiful structured prompt for the forensic LLM
    prompt = f"""
You are a senior forensic intelligence analyst specializing in counter-fraud, network topology, and suspicious activity profiling.

You are given several analytical JSON outputs generated by our automated data pipeline (Graph Topology Summary, Rule Validation Flags, Person Risk Profiles, Relationship Risk Profiles, and Chronological Timeline Reconstruction). Your goal is to synthesize these raw insights into a single, cohesive, premium, human-readable forensic investigation report.

---

### INPUT DATA CONTEXT

#### 1. Graph Summary (Centrality & Network Topology metrics)
```json
{json.dumps(graph_summary, indent=2)}
```

#### 2. Person Risk Profiles (Confidence-Weighted Risk Scores & Explanations)
```json
{json.dumps(person_profiles, indent=2)}
```

#### 3. Relationship Risk Profiles (Suspicious Connections & Shared Resources)
```json
{json.dumps(relationship_profiles, indent=2)}
```

#### 4. Rule Validation Flags (Deterministic suspicious alerts triggered)
```json
{json.dumps(rule_validation, indent=2)}
```

#### 5. Chronological Timeline Reconstruction (Chronological scenes of actions)
```json
{json.dumps(timeline, indent=2)}
```

---

### REPORT FORMAT GUIDELINES

Generate a highly thorough, detailed, and structured investigation report. Please write the output exclusively in markdown, formatting it strictly according to the following layout:

# FORENSIC INVESTIGATION REPORT

## Executive Summary
* Provide a high-level case narrative of what occurred (e.g. suspicious activity patterns observed).
* Detail key case findings, their operational impact, and the significance of the coordinated interactions.
* Ground all claims strictly on the provided telecom communication, location rendezvouses, and circular or sub-threshold banking transfers.

## Key Individuals & Asset Profiling
* Profile all key individuals (e.g. Rahul, Arjun, Vikram, etc.) and accounts/assets.
* Incorporate their graph network centrality scores (e.g., degree centrality, betweenness centrality) and explain what these metrics represent about their relative influence/control over the suspicious network.
* Highlight their observed roles (e.g., fund distributor, central communicator, co-locating coordinator).

## Suspicious Activities & Pattern Matching
* Explain the specific deterministic alerts triggered in the Rule Validation layer.
* Break down each alert pattern (such as sub-threshold financial smurfing, telecom burst communications, physical rendezvous/co-location near Park Street, or cross-source corroboration across 3+ channels).
* Detail the mechanics of how the suspicious pattern was executed, citing amounts, dates, specific source channels (bank, email, chat, GPS, telecom), and the operational risk.

## Timeline Narrative Reconstruction
* Transform the raw chronological scene chunks into a clean, smooth, readable narrative timeline.
* Detail what took place sequentially (e.g., initial comms, travel/GPS co-location logs, subsequent banking transfers/smurfing).
* Use chronological bold headings or bullet points, converting raw timestamps into a natural narrative arc that investigators can easily grasp.

## Investigation Recommendations & Next Steps
* Provide a list of actionable, prioritized next steps.
* Be concrete: recommend checking CCTV cameras at specific locations during co-location windows, requesting official bank KYC records for active transfer accounts (e.g. ACC1001), auditing device logs, or executing formal interviews based on centrality rankings.

---

Ground all names, numbers, amounts, and dates exactly in the provided context. Maintain a highly professional, objective, and analytical tone suitable for law enforcement or senior corporate security directors.
"""

    output_path = LOCAL_OUTPUTS_DIR / "investigation_report.md"
    
    try:
        # Run Gemini
        print("[Gemini Engine] Submitting context to Gemini API...")
        report_markdown = generate_report(prompt)
        
        print(f"[Gemini Engine] Writing report to {output_path}")
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report_markdown)
            
        print("[Gemini Engine] [OK] Success! Forensic report generated successfully.")
        
    except Exception as e:
        print(f"[Gemini Engine] Failed to generate report (likely due to Gemini API rate limits/quota): {e}")
        # Generate a high-quality fallback report using the generated assets so the pipeline succeeds
        fallback_md = f"""# Forensic Investigation Report (Fallback)

**Status:** Generated via local pipeline fallback (Gemini API limit reached).
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Executive Summary
The TATVA automated pipeline successfully preprocessed the evidence, resolved identities, and built the knowledge graph. However, the advanced narrative generation was bypassed due to API quota limitations.

### Key Metrics
- Ingestion, entity resolution, and network centrality calculations completed successfully.
- Risk validation logic ran and generated risk scores.
- Timeline reconstruction completed.

*Please review the Risk Profiles and Interactive Timeline panels directly in the UI dashboard for complete, structured analytical insights.*
"""
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(fallback_md)
        print("[Gemini Engine] Fallback report generated successfully.")


if __name__ == "__main__":
    run_engine()
